### ISSUE TITLE
Possibility to work on specific challenges, instead of all at the same time

### ISSUE THREAD

**Issue by mrturkmencom** [aau-network-security/haaukins#379]
**Is your feature request related to a problem? Please describe.**
Currently,  when an event is created the specified challenges starts to run which creates polluted environment in frontend instance (on kali) by having multiple ip addresses. 

**Describe the solution you'd like**

A solution could be having a step by step mechanism, where challenges will be shown when presented challenges have been solved on foreground, so, initially first step will (which may include different challenges in more or less same level) be solved and other steps will be continued to solved. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jbjjbjjbj** [comment]
Hi i'm currently implementing this. 

My idea is to create a sort of sequence of steps each refering to exercises.
It could be structured something like this. 

```yaml
plays:
    - tag: jan2020schoolevent
      steps:
          - name: The crazy part
            description: > 
                Here you **must** do some stuff in this order
                - Do the thing
                - Profit?
            exercises:
                - sql
                - scan
                - hb
          - name: The easy part
            description: >
                If you can do these you are crazy.
            exercises:
                - mitm
                - csrf
                - scan
            requires: 1
          - name: Finish
            description: >
                Well done here are some usefull characters

                ```
                d}Y;,B3}=6*&cag#
                ```
            requires: 2
```
